
const actionsTypesQuestions={
    LOADING :"LOADING",
    LOAD_SUCCESS:"LOAD_SUCCESS",
    LOAD_FAILURE:"LOAD_FAILURE",
    DELETE_FAVORITE_SUCCESS:"DELETE_FAVORITE_SUCCESS",
    ADD_FAVORITE:"ADD_FAVORITE"
}


export default actionsTypesQuestions